apiVersion: cnad.gofound.nl/v1alpha1
kind: CDTarget
metadata:
  name: cdtarget-agent
  namespace: test
spec:
  agentImage: bartvanbenthem/azagent:v2.211.1
  minReplicaCount: 2
  maxReplicaCount: 5
  config:
    url: https://dev.azure.com/DevOps-SST
    poolName: poc-pool
  tokenRef: cdtarget-token
  proxyRef: cdtarget-proxy
  caCertRef: cdtarget-ca
  podSelector:
    app: cdtarget-agent 
  ip:
  - 10.0.0.1
  - 10.0.0.2