# permissions for end users to view cdtargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cdtarget-viewer-role
rules:
- apiGroups:
  - cnad.gofound.nl
  resources:
  - cdtargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cnad.gofound.nl
  resources:
  - cdtargets/status
  verbs:
  - get
