apiVersion: cnad.gofound.nl/v1alpha1
kind: CDTarget
metadata:
  name: cdtarget-agent-keda
  namespace: test
spec:
  agentImage: bartvanbenthem/azagent-keda:latest
  minReplicaCount: 1
  maxReplicaCount: 5
  config:
    url: https://dev.azure.com/DevOps-SST
    poolName: poc-pool
  tokenRef: cdtarget-token
  caCertRef: cdtarget-ca
  env:
  - name: INJECTED_ADDITIONAL_ENV
    value: example-env
  additionalSelector:
    app: cdtarget-agent
  ip:
  - 10.0.0.1
  - 10.0.0.2