apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdtarget-agent
  labels:
    app: cdtarget-agent
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: cdtarget-agent
  template:
    metadata:
      labels:
        app: cdtarget-agent
    spec:
      containers:
      - name: agent
        image: bartvanbenthem/agent:latest
        env:
          - name: AZP_POOL
          valueFrom:
            configMapKeyRef:
              name: cdtarget-agent-config
              key: AZP_POOL
          - name: AZP_URL
          valueFrom:
            configMapKeyRef:
              name: cdtarget-agent-config
              key: AZP_URL
          - name: AZP_WORK
          valueFrom:
            configMapKeyRef:
              name: cdtarget-agent-config
              key: AZP_WORK
          - name:  AZP_AGENT_NAME
          valueFrom:
            configMapKeyRef:
              name: cdtarget-agent-config
              key:  AZP_AGENT_NAME
          - name:  AGENT_MTU_VALUE
          valueFrom:
            configMapKeyRef:
              name: cdtarget-agent-config
              key:  AGENT_MTU_VALUE         
          - name: CDTARGET_TOKEN
            valueFrom:
              secretKeyRef:
                name: cdtarget-token
                key: CDTARGET_TOKEN
          - name: HTTP_PROXY
            valueFrom:
              secretKeyRef:
                name: cdtarget-proxy
                key: HTTP_PROXY
          - name: HTTPS_PROXY
            valueFrom:
              secretKeyRef:
                name: cdtarget-proxy
                key: HTTPS_PROXY
          - name: PROXY_USER
            valueFrom:
              secretKeyRef:
                name: cdtarget-proxy
                key: PROXY_USER
          - name: PROXY_PW
            valueFrom:
              secretKeyRef:
                name: cdtarget-proxy
                key: PROXY_PW
          - name: PROXY_URL
            valueFrom:
              secretKeyRef:
                name: cdtarget-proxy
                key: PROXY_URL
          - name: FTP_PROXY
            valueFrom:
              secretKeyRef:
                name: cdtarget-proxy
                key: FTP_PROXY
          - name: NO_PROXY
            valueFrom:
              secretKeyRef:
                name: cdtarget-proxy
                key: NO_PROXY
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: cdtarget-volume
      volumes:
      - name: cdtarget-volume
        hostPath:
          path: /var/run/docker.sock